[project]
name = "greenlandweatherdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "panda>=0.3.1",
    "pandas>=2.3.2",
    "windrose>=1.9.2",
]
